### ISSUE TITLE
I test the demo part-1, then mvn clean package, I get the following error message

### ISSUE THREAD

**Issue by timloo0710** [cor3000/zk-wizard-example#1]
$ mvn clean package
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building The wizardexample Project 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.zkoss.zk:zkmax:jar:8.0.0.FL.20150827-Eval is missing, no dependency information available
[WARNING] The POM for org.zkoss.zk:zkplus:jar:8.0.0.FL.20150827-Eval is missing, no dependency information available
[WARNING] The POM for org.zkoss.zk:zuti:jar:8.0.0.FL.20150827-Eval is missing, no dependency information available
[WARNING] The POM for org.zkoss.zk:zhtml:jar:8.0.0.FL.20150827-Eval is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.738 s
[INFO] Finished at: 2016-10-15T23:17:03+08:00
[INFO] Final Memory: 8M/75M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wizardexample: Could not resolve dependencies for project zk.example:wizardexample:war:1.0-SNAPSHOT: The following artifacts could not be resolved: org.zkoss.zk:zkmax:jar:8.0.0.FL.20150827-Eval, org.zkoss.zk:zkplus:jar:8.0.0.FL.20150827-Eval, org.zkoss.zk:zuti:jar:8.0.0.FL.20150827-Eval, org.zkoss.zk:zhtml:jar:8.0.0.FL.20150827-Eval: Failure to find org.zkoss.zk:zkmax:jar:8.0.0.FL.20150827-Eval in http://mavensync.zkoss.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of ZK CE has elapsed or updates are forced -> [Help 1]

Is there any help?

**Comment by cor3000** [comment]
thanks for the hint.
The FL versions have been cleaned up and I'll update the example code soon.
In the mean time, please use a released Eval version:
e.g. 8.0.3-Eval

simply change the <zk.version> property see: [pom.xml Line 8 in master](https://github.com/cor3000/zk-wizard-example/blob/part-4/pom.xml#L8)

**Comment by cor3000** [comment]
part1 ~ 4 are now upgraded to use version 8.0.3-Eval
e.g:
https://github.com/cor3000/zk-wizard-example/tree/part-1
https://github.com/cor3000/zk-wizard-example/blob/part-1/pom.xml#L8
